apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:
    app: db
spec:
  containers:
  - name: mysql-volume
    image: mysql
    env:
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
      - name: MYSQL_ROOT_PASSWORD
        value: password
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: db-volume
  volumes:
  - name: db-volume
    # Storage on the environnement
    hostPath:
      path: /data-volume
      type: Directory